config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
  }

  devise_for :end_users, controllers: {
    sessions: 'end_users/sessions',
    passwords: 'end_users/passwords',
    registrations: 'end_users/registrations'
  }

  root to: 'homes#top'
  get 'homes/about' => 'homes#about'
  get 'homes/random' => 'homes#random'

  #ユーザー側のルーティング
  get 'quotes/user_posts' => 'quotes#user_posts' #ユーザーの投稿と管理者側の投稿を分けるためにページも別々に
  get 'end_users/:id/withdrawal' => 'end_users#withdrawal', as: 'withdrawal' #退会確認ページ
  patch 'end_users/:id/unsubscribe' => 'end_users#unsubscribe', as: 'unsubscribe' #退会フラグを更新する
  get 'end_users/:id/following' => 'end_users#following', as: 'follow_list'
  get 'end_users/:id/followers' => 'end_users#followers', as: 'follower_list'

  resources :quotes do
    resource :evaluations, only: [:create]
    resources :comments, only: [:create, :destroy]
  end
  resources :end_users, only: [:show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
  end
  resources :person_profiles, only: [:index, :show]
  resources :contacts, only: [:new, :create]

  #管理者側のルーティング
  namespace :admins do
    get 'quotes/user_posts' => 'quotes#user_posts'
    resources :quotes

    resources :end_users, only: [:index, :show, :edit, :update]
    resources :categories, only: [:index, :create, :update, :destroy]
    resources :person_profiles
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :admin, optional: true
  belongs_to :end_user, optional: true
  belongs_to :person_profile, optional: true
  belongs_to :category
  has_many :evaluations, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :good_evaluations, lambda { where('status = 0')}, class_name: 'Evaluation'

  attachment :person_image

  validates :person_name,
    presence: true,
    length: { maximum: 20 },
    unless: -> { admin } #adminはこのバリデーションを適用しない

  validates :content,
    presence: true,
    length: { maximum: 100 }

  def evaluationed_good_by?(end_user)
    evaluations.where(end_user_id: end_user.id).where(status: 'good').exists?
  end

  def evaluationed_bad_by?(end_user)
    evaluations.where(end_user_id: end_user.id).where(status: 'bad').exists?
  end

  def evaluation_good
    evaluations.where(status: 'good')
  end

  def evaluation_bad
    evaluations.where(status: 'bad')
  end

end

app/controllers/admins/quotes_controller.rb
class Admins::QuotesController < ApplicationController
  before_action :authenticate_admin!
  def new
    @quote = Quote.new
    @categories = Category.all
    @persons = PersonProfile.all
  end

  def create
    quote = Quote.new(quote_params)
    if quote.save
      redirect_to admins_quote_path(quote.id)
    else
      render :new
    end
  end

  def index
    @quotes = Quote.where.not(admin_id: nil).order(created_at: "DESC").all.page(params[:page]).per(12)
  end

  def user_posts
    @quotes = Quote.where.not(end_user_id: nil).order(created_at: "DESC").all.page(params[:page]).per(12)
  end

  def show
    @quote = Quote.find(params[:id])
    @comments = @quote.comments.order(created_at: "DESC").all.page(params[:page]).per(10)
  end

  def edit
    @quote = Quote.find(params[:id])
    @categories = Category.all
    @persons = PersonProfile.all
  end

  def update
    quote = Quote.find(params[:id])
    quote.update(quote_params)
    redirect_to admins_quote_path(quote.id)
  end

  def destroy
    quote = Quote.find(params[:id])
    quote.destroy
    redirect_to admins_quotes_path
  end

  private

  def quote_params
    params.require(:quote).permit(:admin_id, :category_id, :person_profile_id, :content )
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :authenticate_end_user!, only: [:new, :create, :user_posts, :edit, :update, :destroy]
  def new
    @quote = Quote.new
    @categories = Category.all
  end

  def create
    quote = Quote.new(quote_params)
    if quote.save
      redirect_to quote_path(quote.id)
    else
      flash[:danger] = quote.errors.full_messages
      redirect_to new_quote_path
    end
  end

  def index
    if params[:quote_selection] == '偉人名(迷)言'
      if params[:word]
        @quotes = Quote.where.not(admin_id: nil).where('content LIKE?', "%#{params[:word]}%").order(created_at: "DESC").all.page(params[:page]).per(12)
        if params[:evaluation_ranking] == 'good'
          @quotes = Quote.left_joins(:good_evaluations).where.not(admin_id: nil).order("cnt_good desc").group(:id).select("quotes.*, count(evaluations.quote_id) cnt_good").all.page(params[:page]).per(12)
        end
      end
    elsif params[:quote_selection] == 'ユーザー名(迷)言'
      if params[:word]
        @quotes = Quote.where.not(end_user_id: nil).where('content LIKE?', "%#{params[:word]}%").order(created_at: "DESC").all.page(params[:page]).per(12)
      end
      render '/quotes/user_posts'
    else
      @quotes = Quote.where.not(admin_id: nil).order(created_at: "DESC").all.page(params[:page]).per(12)
      if params[:evaluation_ranking] == 'good'
        @quotes = Quote.left_joins(:good_evaluations).where.not(admin_id: nil).order("cnt_good desc").group(:id).select("quotes.*, count(evaluations.quote_id) cnt_good").all.page(params[:page]).per(12)
      end
    end
  end

  def user_posts
    @quotes = Quote.where.not(end_user_id: nil).order(created_at: "DESC").all.page(params[:page]).per(12)
    if params[:evaluation_ranking] == 'good'
      @quotes = Quote.left_joins(:good_evaluations).where.not(end_user_id: nil).order("cnt_good desc").group(:id).select("quotes.*, count(evaluations.quote_id) cnt_good").all.page(params[:page]).per(12)
    end
  end

  def show
    @quote = Quote.find(params[:id])
    @end_user = @quote.end_user
    @comment = Comment.new
    @comments = @quote.comments.order(created_at: "DESC").page(params[:page]).per(10)
  end

  def edit
    @quote = Quote.find(params[:id])
    @categories = Category.all
  end

  def update
    quote = Quote.find(params[:id])
    if quote.update(quote_params)
      redirect_to quote_path(quote.id)
    else
      flash[:errors] = quote.errors.full_messages
      redirect_to edit_quote_path(quote.id)
    end
  end

  def destroy
    quote = Quote.find(params[:id])
    quote.destroy
    redirect_to quotes_path
  end

  private

  def quote_params
    params.require(:quote).permit(:end_user_id, :category_id, :person_image, :person_name, :content)
  end
end

app/helpers/admins/quotes_helper.rb
module Admins::QuotesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/edit.html.erb
<div class="container">
  <%= form_with model:@quote, local: true do |f| %>
    <div class="quote-input-area">
      <h3 class="text-center">~ 名(迷)言編集 ~</h3>
      <div class="text-center bg-white pt-2 pb-2">
        <%= attachment_image_tag @quote, :person_image, fallback: "no_image.png", size: "150x150", id: "preview" %><br>
        <%= f.attachment_field :person_image %>
      </div>
      <div class="mt-3">
        <% if flash[:errors] != nil %>
          <ul>
            <% flash[:errors].each do |message| %>
              <font color="red"><li><%= message %></li></font>
            <% end %>
          </ul>
        <% end %>
        <%= f.collection_select :category_id, @categories, :id, :name %><br>
        <div class="quote-input-form">
          <%= f.label :person_name, "発言者名 (20文字以内)" %><br>
          <%= f.text_field :person_name, class: "quote-form" %>
        </div>
        <div class="quote-input-form">
          <%= f.label :content, "名（迷）言 (100文字以内)" %><br>
          <%= f.text_area :content, class: "quote-form" %><br>
        </div>
        <div class="text-center">
          <%= f.submit "更新", class: "btn btn-success", style: "width: 35%;" %>
          <%= link_to "削除", quote_path(@quote.id), method: :delete, class: "btn btn-danger", style: "width: 35%;" , "data-confirm" => "本当に削除しますか？"%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/quotes/index.html.erb
<div class="container">
  <%= link_to  "GOOD多い順", quotes_path(evaluation_ranking: 'good') %>
  <div class="row row-cols-xl-3 row-cols-la-2 row-cols-md-2 row-cols-1">
    <% @quotes.each do |quote| %>
      <div class="col">
        <div class="person-quote fly shadow">
            <%= link_to quote_path(quote.id) do %>
              <div class="person-profile d-flex flex-row">
                <div>
                  <%= attachment_image_tag quote.person_profile, :image, fallback: "no_image.png", size: "60x60" %>
                </div>
                <div class="mx-3">
                  <%= quote.person_profile.name %><br>
                  <% if quote.category.name == "ポジティブ" %>
                    <span class="positive-icon"><%= quote.category.name %></span>
                  <% else %>
                    <span class="negative-icon"><%= quote.category.name %></span>
                  <% end %>
                  <%= l quote.created_at %>
                </div>
              </div>
              <div class="person-content">
                <%= quote.content.truncate(50, omission: '...') %>
              </div>
            <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex align-items-center justify-content-center"><%= paginate @quotes %></div>
</div>

app/views/quotes/new.html.erb
<div class="container">
  <%= form_with model:@quote, local: true do |f| %>
    <div class="quote-input-area">
      <h3 class="text-center">~ 名(迷)言投稿 ~</h3>
      <p class="border border-secondary px-2">画像はjpegを推奨します。<br>
        pngファイルですと背景と同化してしまい画像が見えなくなってしまう可能性があります。<br>
      </p>
      <div class="text-center bg-white pt-2 pb-2">
        <%= attachment_image_tag @quote, :person_image, fallback: "no_image.png", size: "150x150", id: "preview" %><br>
        <%= f.attachment_field :person_image %>
      </div>
      <div class="mt-3">
        <% if flash[:danger] != nil %>
          <ul>
            <% flash[:danger].each do |message| %>
              <font color="red"><li><%= message %></li></font>
            <% end %>
          </ul>
        <% end %>
        <%= f.collection_select :category_id, @categories, :id, :name %><br>
        <div class="quote-input-form">
          <%= f.label :person_name, "発言者名 (20文字以内)" %><br>
          <%= f.text_field :person_name, class: "quote-form" %>
        </div>
        <div class="quote-input-form">
          <%= f.label :content, "名(迷)言 (100文字以内)" %><br>
          <%= f.text_area :content, class: "quote-form" %><br>
        </div>
        <div class="text-center">
          <%= f.hidden_field :end_user_id, value: current_end_user.id %>
          <%= f.submit "名(迷)言を投稿", class: "btn btn-success w-50" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/quotes/show.html.erb
<div class="container">
  <div class="quote-show">
    <h1 class="mx-auto quote"><%= @quote.content %></h1>
      <% if @quote.admin_id %>
        <h5 class="text-right quote">~ <%= link_to @quote.person_profile.name, person_profile_path(@quote.person_profile.id) %> ~</h5>
      <% else %>
        <h5 class="text-right quote">~ <%= @quote.person_name %> ~</h5>
      <% end %>
    <div class="row mt-3 d-flex align-items-center mx-auto">
      <div class="col-4 ml-4">
        <% if @quote.admin_id %>
          <%= attachment_image_tag @quote.person_profile, :image, fallback: "no_image_png", size: "100x100" %>
        <% else %>
          <%= attachment_image_tag @quote, :person_image, fallback: "no_image.png", size: "100x100" %>
        <% end %>
      </div>
      <div class="col-6 text-center">
        <% if @quote.category.name == "ポジティブ" %>
          <span class="positive-icon"><%= @quote.category.name %></span>
        <% else %>
          <span class="negative-icon"><%= @quote.category.name %></span>
        <% end %>
        <span class="h4"><%= l @quote.created_at %></span><br>

        <span id="evaluation"><%= render 'evaluations/form', quote: @quote %></span>

        <% if @quote.end_user_id %>
          <% if current_end_user.id == @quote.end_user.id %>
            <%= link_to "編集", edit_quote_path(@quote.id), class: "btn btn-success" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="mt-4">
    <% if @quote.end_user_id %>
      <div class="d-flex flex-row align-items-center">
        <div class="mr-1">
          <%= attachment_image_tag @quote.end_user, :image, fallback: "no_image.png", size: "50x50" %>
        </div>
        <div>
          　<%= link_to @quote.end_user.name, end_user_path(@quote.end_user_id) %><br>
          < 私が投稿しました。<br>
          <span id="relationship"><%= render 'relationships/follow', end_user: @end_user %></span>
        </div>
      </div>
    <% end %>
    <div class="comment-area mt-3">
      <h5>コメント</h5>
      <div id="comment_error"><%= render 'comments/error', comment: @comment %></div>
      <% if end_user_signed_in? %>
        <%= form_with(model:[@quote, @comment]) do |f| %>
          <%= attachment_image_tag current_end_user, :image, fallback: "no_image.png", size: "50x50" %>
          <%= f.text_field :comment, placeholder: "コメントする", class: "comment-form" %>
          <%= f.submit "送信", class: "btn btn-primary"%>
        <% end %>
      <% end %>
      <div id="comment-area"><%= render 'comments/form', comments: @comments %></div>
      <div class="d-flex align-items-center justify-content-center"><%= paginate @comments %></div>
    </div>
  </div>
</div>

app/views/quotes/user_posts.html.erb
<div class="container">
  <%= link_to  "GOOD多い順", quotes_user_posts_path(evaluation_ranking: 'good') %>
  <div class="row row-cols-xl-3 row-cols-la-2 row-cols-md-2 row-cols-1">
      <% @quotes.each do |quote| %>
      <div class="col">
        <div class="person-quote fly shadow">
            <%= link_to quote_path(quote.id) do %>
              <div class="person-profile d-flex flex-row">
                <div>
                  <%= attachment_image_tag quote, :person_image, fallback: "no_image.png", size: "90x90" %>
                </div>
                <div class="mx-3">
                  <%= quote.person_name %><br>
                  <% if quote.category.name == "ポジティブ" %>
                    <span class="positive-icon"><%= quote.category.name %></span>
                  <% else %>
                    <span class="negative-icon"><%= quote.category.name %></span>
                  <% end %>
                  <%= l quote.created_at %>
                </div>
              </div>
              <div class="person-content">
                <%= quote.content.truncate(50, omission: '...') %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
  </div>
  <div class="d-flex align-items-center justify-content-center"><%= paginate @quotes %></div>
</div>