config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
  }

  devise_for :end_users, controllers: {
    sessions: 'end_users/sessions',
    passwords: 'end_users/passwords',
    registrations: 'end_users/registrations'
  }

  root to: 'homes#top'
  get 'homes/about' => 'homes#about'
  get 'homes/random' => 'homes#random'

  #ユーザー側のルーティング
  get 'quotes/user_posts' => 'quotes#user_posts' #ユーザーの投稿と管理者側の投稿を分けるためにページも別々に
  get 'end_users/:id/withdrawal' => 'end_users#withdrawal', as: 'withdrawal' #退会確認ページ
  patch 'end_users/:id/unsubscribe' => 'end_users#unsubscribe', as: 'unsubscribe' #退会フラグを更新する
  get 'end_users/:id/following' => 'end_users#following', as: 'follow_list'
  get 'end_users/:id/followers' => 'end_users#followers', as: 'follower_list'

  resources :quotes do
    resource :evaluations, only: [:create]
    resources :comments, only: [:create, :destroy]
  end
  resources :end_users, only: [:show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
  end
  resources :person_profiles, only: [:index, :show]
  resources :contacts, only: [:new, :create]

  #管理者側のルーティング
  namespace :admins do
    get 'quotes/user_posts' => 'quotes#user_posts'
    resources :quotes

    resources :end_users, only: [:index, :show, :edit, :update]
    resources :categories, only: [:index, :create, :update, :destroy]
    resources :person_profiles
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "EndUser"
  belongs_to :following, class_name: "EndUser"
  validates :follower_id, presence: true
  validates :following_id, presence: true
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_end_user!
  def create
    @end_user = EndUser.find(params[:end_user_id])
    current_end_user.follow(@end_user)
  end

  def destroy
    @end_user = Relationship.find(params[:id]).following
    current_end_user.unfollow(@end_user)
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.erb
<% unless current_end_user == end_user %>
  <% if current_end_user.following?(end_user) %>
    <%= link_to end_user_relationship_path(end_user_id: end_user.id, id: current_end_user.following_relationships.find_by(following_id: end_user.id).id), method: :delete, remote: true do %>
      <div class="unfollow btn">フォロー解除</div>
    <% end %>
  <% else %>
    <%= link_to end_user_relationships_path(end_user_id: end_user.id), method: :post, remote: true do %>
      <div class="follow btn">フォローする</div>
    <% end %>
  <% end %>
<% end %>

app/views/relationships/create.js.erb
$('#relationship').html("<%= j(render 'relationships/follow', end_user: @end_user) %>")

app/views/relationships/destroy.js.erb
$('#relationship').html("<%= j(render 'relationships/follow', end_user: @end_user) %>")