config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
  }

  devise_for :end_users, controllers: {
    sessions: 'end_users/sessions',
    passwords: 'end_users/passwords',
    registrations: 'end_users/registrations'
  }

  root to: 'homes#top'
  get 'homes/about' => 'homes#about'
  get 'homes/random' => 'homes#random'

  #ユーザー側のルーティング
  get 'quotes/user_posts' => 'quotes#user_posts' #ユーザーの投稿と管理者側の投稿を分けるためにページも別々に
  get 'end_users/:id/withdrawal' => 'end_users#withdrawal', as: 'withdrawal' #退会確認ページ
  patch 'end_users/:id/unsubscribe' => 'end_users#unsubscribe', as: 'unsubscribe' #退会フラグを更新する
  get 'end_users/:id/following' => 'end_users#following', as: 'follow_list'
  get 'end_users/:id/followers' => 'end_users#followers', as: 'follower_list'

  resources :quotes do
    resource :evaluations, only: [:create]
    resources :comments, only: [:create, :destroy]
  end
  resources :end_users, only: [:show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
  end
  resources :person_profiles, only: [:index, :show]
  resources :contacts, only: [:new, :create]

  #管理者側のルーティング
  namespace :admins do
    get 'quotes/user_posts' => 'quotes#user_posts'
    resources :quotes

    resources :end_users, only: [:index, :show, :edit, :update]
    resources :categories, only: [:index, :create, :update, :destroy]
    resources :person_profiles
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :admin, optional: true
  belongs_to :end_user, optional: true
  belongs_to :person_profile, optional: true
  belongs_to :category
  has_many :evaluations, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :good_evaluations, lambda { where('status = 0')}, class_name: 'Evaluation'

  attachment :person_image

  validates :person_name,
    presence: true,
    length: { maximum: 20 },
    unless: -> { admin } #adminはこのバリデーションを適用しない

  validates :content,
    presence: true,
    length: { maximum: 100 }

  def evaluationed_good_by?(end_user)
    evaluations.where(end_user_id: end_user.id).where(status: 'good').exists?
  end

  def evaluationed_bad_by?(end_user)
    evaluations.where(end_user_id: end_user.id).where(status: 'bad').exists?
  end

  def evaluation_good
    evaluations.where(status: 'good')
  end

  def evaluation_bad
    evaluations.where(status: 'bad')
  end

end

app/controllers/admins/quotes_controller.rb
class Admins::QuotesController < ApplicationController
  before_action :authenticate_admin!
  def new
    @quote = Quote.new
    @categories = Category.all
    @persons = PersonProfile.all
  end

  def create
    quote = Quote.new(quote_params)
    if quote.save
      redirect_to admins_quote_path(quote.id)
    else
      render :new
    end
  end

  def index
    @quotes = Quote.where.not(admin_id: nil).order(created_at: "DESC").all.page(params[:page]).per(12)
  end

  def user_posts
    @quotes = Quote.where.not(end_user_id: nil).order(created_at: "DESC").all.page(params[:page]).per(12)
  end

  def show
    @quote = Quote.find(params[:id])
    @comments = @quote.comments.order(created_at: "DESC").all.page(params[:page]).per(10)
  end

  def edit
    @quote = Quote.find(params[:id])
    @categories = Category.all
    @persons = PersonProfile.all
  end

  def update
    quote = Quote.find(params[:id])
    quote.update(quote_params)
    redirect_to admins_quote_path(quote.id)
  end

  def destroy
    quote = Quote.find(params[:id])
    quote.destroy
    redirect_to admins_quotes_path
  end

  private

  def quote_params
    params.require(:quote).permit(:admin_id, :category_id, :person_profile_id, :content )
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :authenticate_end_user!, only: [:new, :create, :user_posts, :edit, :update, :destroy]
  def new
    @quote = Quote.new
    @categories = Category.all
  end

  def create
    quote = Quote.new(quote_params)
    if quote.save
      redirect_to quote_path(quote.id)
    else
      flash[:danger] = quote.errors.full_messages
      redirect_to new_quote_path
    end
  end

  def index
    if params[:quote_selection] == '偉人名(迷)言'
      if params[:word]
        @quotes = Quote.where.not(admin_id: nil).where('content LIKE?', "%#{params[:word]}%").order(created_at: "DESC").all.page(params[:page]).per(12)
        if params[:evaluation_ranking] == 'good'
          @quotes = Quote.left_joins(:good_evaluations).where.not(admin_id: nil).order("cnt_good desc").group(:id).select("quotes.*, count(evaluations.quote_id) cnt_good").all.page(params[:page]).per(12)
        end
      end
    elsif params[:quote_selection] == 'ユーザー名(迷)言'
      if params[:word]
        @quotes = Quote.where.not(end_user_id: nil).where('content LIKE?', "%#{params[:word]}%").order(created_at: "DESC").all.page(params[:page]).per(12)
      end
      render '/quotes/user_posts'
    else
      @quotes = Quote.where.not(admin_id: nil).order(created_at: "DESC").all.page(params[:page]).per(12)
      if params[:evaluation_ranking] == 'good'
        @quotes = Quote.left_joins(:good_evaluations).where.not(admin_id: nil).order("cnt_good desc").group(:id).select("quotes.*, count(evaluations.quote_id) cnt_good").all.page(params[:page]).per(12)
      end
    end
  end

  def user_posts
    @quotes = Quote.where.not(end_user_id: nil).order(created_at: "DESC").all.page(params[:page]).per(12)
    if params[:evaluation_ranking] == 'good'
      @quotes = Quote.left_joins(:good_evaluations).where.not(end_user_id: nil).order("cnt_good desc").group(:id).select("quotes.*, count(evaluations.quote_id) cnt_good").all.page(params[:page]).per(12)
    end
  end

  def show
    @quote = Quote.find(params[:id])
    @end_user = @quote.end_user
    @comment = Comment.new
    @comments = @quote.comments.order(created_at: "DESC").page(params[:page]).per(10)
  end

  def edit
    @quote = Quote.find(params[:id])
    @categories = Category.all
  end

  def update
    quote = Quote.find(params[:id])
    if quote.update(quote_params)
      redirect_to quote_path(quote.id)
    else
      flash[:errors] = quote.errors.full_messages
      redirect_to edit_quote_path(quote.id)
    end
  end

  def destroy
    quote = Quote.find(params[:id])
    quote.destroy
    redirect_to quotes_path
  end

  private

  def quote_params
    params.require(:quote).permit(:end_user_id, :category_id, :person_image, :person_name, :content)
  end
end

app/helpers/admins/quotes_helper.rb
module Admins::QuotesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/admins/quotes/edit.html.erb
<div class="container">
  <h1>名言情報編集</h1>
  <%= form_with model:@quote, url: admins_quote_path(@quote), local: true do |f| %>
  <% if @quote.end_user_id %>
    <%= attachment_image_tag @quote, :person_image, :fill, 150, 150, fallback: "no_image.png", size: "100x100" %>
    <%= f.attachment_field :person_image %>
  <% end %>
    <table>
      <tr>
        <th><%= f.label :category_id, "ポジティブorネガティブ" %></th>
        <th><%= f.collection_select :category_id, @categories, :id, :name %></th>
      </tr>
      <tr>
        <% if @quote.admin_id %>
          <th><%= f.label :person_profile_id, "偉人情報選択" %></th>
          <th><%= f.collection_select :person_profile_id, @persons, :id, :name %></th>
        <% else %>
          <th><%= f.label :person_name, "発言者名" %></th>
          <th><%= f.text_field :person_name %><th>
        <% end %>
      </tr>
      <tr>
        <th><%= f.label :content, "名言内容" %></th>
        <th><%= f.text_area :content %></th>
      </tr>
      <tr>
        <th></th>
        <th><%= f.submit "更新", class: "btn btn-success"  %></th>
      </tr>
    </table>
  <% end %>
</div>

app/views/admins/quotes/index.html.erb
<div class="container">
  <h1>偉人名言一覧（管理者側）</h1>
  <%= link_to "名言新規投稿", new_admins_quote_path %>
  <table class="table bg-white">
    <tr>
      <th>投稿日</th>
      <th>偉人画像</th>
      <th>偉人名</th>
      <th>カテゴリ</th>
      <th>名言</th>
      <th>評価</th>
    </tr>
    <% @quotes.each do |quote| %>
    <tr>
      <th><%= l quote.created_at %></th>
      <th><%= attachment_image_tag quote.person_profile, :image, :fill, 70, 70, fallback: "no_image.png", size: '70x70' %></th>
      <th><%= link_to quote.person_profile.name, admins_person_profile_path(quote.person_profile.id) %></th>
      <th><%= quote.category.name %></th>
      <th><%= link_to quote.content, admins_quote_path(quote.id) %></th>
      <th>
        G<%= quote.evaluation_good.count %>
        B<%= quote.evaluation_bad.count %>
      </th>
    </tr>
    <% end %>
  </table>
  <div class="d-flex align-items-center justify-content-center"><%= paginate @quotes %></div>
</div>

app/views/admins/quotes/new.html.erb
<div class="container">
  <h1>名言投稿</h1>
  <%= form_with model:@quote, url: admins_quotes_path, local: true do |f| %>
    <div class="admin_quote_category">
      <%= f.label :category_id, "ポジティブorネガティブ" %>
      <%= f.collection_select :category_id, @categories, :id, :name %>
    </div>
    <div class="admin_quote_person">
      <%= f.label :person_profile_id, "偉人情報選択" %>
      <%= f.collection_select :person_profile_id, @persons, :id, :name %>
    </div>
    <div class="admin_quote_content">
      <%= f.label :content, "名言内容" %><br>
      <%= f.text_area :content %>
    </div>
    <%= f.hidden_field :admin_id, value: current_admin.id %>
    <%= f.submit "投稿", class: "btn btn-success"  %>
  <% end %>
</div>

app/views/admins/quotes/show.html.erb
<div class="container">
  <h1>名言詳細</h1>
  <div class="row">
    <div class="mb-2">
      <% if @quote.admin_id %>
        <%= attachment_image_tag @quote.person_profile, :image, fallback: "no_image_png", size: "100x100" %>
      <% else %>
        <%= attachment_image_tag @quote, :person_image, fallback: "no_image.png", size: "100x100" %>
      <% end %>
    </div>
    <div class="d-flex align-items-center">
      <% if @quote.admin_id %>
        <h3><%= link_to @quote.person_profile.name, person_profile_path(@quote.person_profile.id) %></h3>
      <% else %>
        <h3><%= @quote.person_name %></h3>
      <% end %>
    </div>
  </div>
    <div>
      <span class="negative-icon mr-5"><%= @quote.category.name %></span>
      <%= link_to "編集", edit_admins_quote_path(@quote.id), class: "btn btn-success" %>
      <%= link_to "削除", admins_quote_path(@quote.id), method: :delete, class: "btn btn-danger" %><br>
    </div>
    <div class="h4 mt-3"><%= @quote.content %></div>
  <table class="table bg-white">
    <tr>
      <th>投稿日</th>
      <th>コメント</th>
    </tr>
    <% @comments.each do |comment| %>
    <tr>
      <th><%= l comment.created_at %></th>
      <th><%= comment.comment %><%= link_to "削除する", admins_quote_comment_path(comment.quote_id, comment.id), method: :delete %></th>
    </tr>
    <% end %>
  </table>
  <div class="d-flex align-items-center justify-content-center"><%= paginate @comments %></div>
</div>

app/views/admins/quotes/user_posts.html.erb
<div class="container">
  <h1>偉人名言一覧（管理者側）</h1>
  <table class="table bg-white">
    <tr>
      <th>投稿日</th>
      <th>偉人画像</th>
      <th>偉人名</th>
      <th>カテゴリ</th>
      <th>名言</th>
      <th>評価</th>
    </tr>
    <% @quotes.each do |quote| %>
    <tr>
      <th><%= l quote.created_at %></th>
      <th><%= attachment_image_tag quote, :person_image, :fill, 70, 70, fallback: "no_image.png", size: '70x70' %></th>
      <th><%= quote.person_name %></th>
      <th><%= quote.category.name %></th>
      <th><%= link_to quote.content, admins_quote_path(quote.id) %></th>
      <th>
        G<%= quote.evaluation_good.count %>
        B<%= quote.evaluation_bad.count %>
      </th>
    </tr>
    <% end %>
  </table>
  <div class="d-flex align-items-center justify-content-center"><%= paginate @quotes %></div>
</div>