config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
  }

  devise_for :end_users, controllers: {
    sessions: 'end_users/sessions',
    passwords: 'end_users/passwords',
    registrations: 'end_users/registrations'
  }

  root to: 'homes#top'
  get 'homes/about' => 'homes#about'
  get 'homes/random' => 'homes#random'

  #ユーザー側のルーティング
  get 'quotes/user_posts' => 'quotes#user_posts' #ユーザーの投稿と管理者側の投稿を分けるためにページも別々に
  get 'end_users/:id/withdrawal' => 'end_users#withdrawal', as: 'withdrawal' #退会確認ページ
  patch 'end_users/:id/unsubscribe' => 'end_users#unsubscribe', as: 'unsubscribe' #退会フラグを更新する
  get 'end_users/:id/following' => 'end_users#following', as: 'follow_list'
  get 'end_users/:id/followers' => 'end_users#followers', as: 'follower_list'

  resources :quotes do
    resource :evaluations, only: [:create]
    resources :comments, only: [:create, :destroy]
  end
  resources :end_users, only: [:show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
  end
  resources :person_profiles, only: [:index, :show]
  resources :contacts, only: [:new, :create]

  #管理者側のルーティング
  namespace :admins do
    get 'quotes/user_posts' => 'quotes#user_posts'
    resources :quotes

    resources :end_users, only: [:index, :show, :edit, :update]
    resources :categories, only: [:index, :create, :update, :destroy]
    resources :person_profiles
  end
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :quotes, dependent: :destroy
  has_many :evaluations, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :content

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  attachment :image

  validates :name,
    presence: true,
    length: { maximum: 20 }
  validates :introduction,
    length: { maximum: 100 }
  validates :email,
    uniqueness: true

  def following?(other_end_user)
    following_relationships.find_by(following_id: other_end_user.id)
  end

  def follow(other_end_user)
    following_relationships.create(following_id: other_end_user.id)
  end

  def unfollow(other_end_user)
    following_relationships.find_by(following_id: other_end_user.id).destroy
  end

end

app/controllers/admins/end_users_controller.rb
class Admins::EndUsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @end_users = EndUser.all.page(params[:page]).per(12)
  end

  def show
    @end_user = EndUser.find(params[:id])
    @quotes = @end_user.quotes.order(created_at: "DESC").all.page(params[:page]).per(12)
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    end_user = EndUser.find(params[:id])
    end_user.update(end_user_params)
    redirect_to admins_end_user_path(end_user.id)
  end

  private

  def end_user_params
    params.require(:end_user).permit(:email, :name, :image, :introduction, :is_withdrawal)
  end

end

app/controllers/end_users/confirmations_controller.rb
# frozen_string_literal: true

class EndUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/end_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class EndUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/end_users/passwords_controller.rb
# frozen_string_literal: true

class EndUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/end_users/registrations_controller.rb
# frozen_string_literal: true

class EndUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users/sessions_controller.rb
# frozen_string_literal: true

class EndUsers::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    if !!current_end_user && current_end_user&.is_withdrawal != true #ユーザーが存在する場合（true）かつユーザーの退会フラグがfalseの時
      reset_session
      flash[:alert] = "このアカウントは退会済みです。"
      redirect_to request.referer
    end
  end
end

app/controllers/end_users/unlocks_controller.rb
# frozen_string_literal: true

class EndUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController
  before_action :authenticate_end_user!
  def show
    @end_user = EndUser.find(params[:id])
    @quotes = @end_user.quotes.order(created_at: "DESC").all.page(params[:page]).per(12)
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    end_user = EndUser.find(params[:id])
    if  end_user.update(end_user_params)
      redirect_to end_user_path(end_user.id)
    else
      flash[:error] = end_user.errors.full_messages
      redirect_to edit_end_user_path(end_user.id)
    end
  end

  def withdrawal #退会確認ページ
    @end_user = EndUser.find(params[:id])
  end

  def unsubscribe #退会フラグを更新
    end_user = EndUser.find(params[:id])
    end_user.update(is_withdrawal: false)
    reset_session
    flash[:notice] = "ご利用ありがとうございました。"
    redirect_to root_path
  end

  def following
    @end_user = EndUser.find(params[:id])
    @end_users = @end_user.followings.all.page(params[:page]).per(10)
  end

  def followers
    @end_user = EndUser.find_by(id: params[:id])
    @end_users = @end_user.followers.all.page(params[:page]).per(10)
  end

  private

  def end_user_params
    params.require(:end_user).permit(:name, :email, :introduction, :is_withdrawal, :image)
  end

end

app/helpers/admins/end_users_helper.rb
module Admins::EndUsersHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/views/end_users/edit.html.erb
<div class="container">
  <%= form_with model:@end_user, local: true do |f| %>
  <div class="quote-input-area">
    <h3 class="text-center">~ ユーザー情報編集 ~</h3>
    <div class="text-center bg-white pt-2 pb-2">
      <%= attachment_image_tag @end_user, :image, fallback: "no_image.png", size: "150x150", id: "preview" %><br>
      <%= f.attachment_field :image %>
    </div>
    <div class="mt-3">
      <% if flash[:error] != nil %>
        <% flash[:error].each do |message| %>
          <font color="red"><%= message %></font>
        <% end %>
      <% end %>
      <div class="quote-input-form">
        ユーザーネーム (20文字以内)
        <%= f.text_field :name, class: "quote-form" %>
      </div>
      <div class="quote-input-form">
        メールアドレス
        <%= f.text_field :email, class: "quote-form" %>
      </div>
      <div class="quote-input-form">
        自己紹介文 (100文字以内)
        <%= f.text_area :introduction, class: "quote-form" %>
      </div>
      <div class="text-center">
        <%= f.submit "情報を更新", class: "btn btn-success", style: "width: 40%;" %>
        <span class="pl-5"><%= link_to "退会する", withdrawal_path(@end_user.id), class: "btn btn-danger", style: "width: 30%;" %></span>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/end_users/followers.html.erb
<div class="container">
  <div class="row mx-auto">
    <div class="d-flex align-items-center justify-content-center">
      <div class="mr-4"><%= attachment_image_tag @end_user, :image, fallback: "no_image.png", size: "150x150" %></div>
      <div>
        <h3><%= @end_user.name %></h3>
        <p><%= @end_user.introduction %></p>
        <% if current_end_user == @end_user %>
          <%= link_to " プロフィールを編集", edit_end_user_path(@end_user.id), class: "fas fa-edit btn btn-success" %>
        <% end %>
        <span id="relationship"><%= render 'relationships/follow', end_user: @end_user %></span>
      </div>
    </div>
  </div>
  <div class="mypage-container mt-4">
    <ul class="mypage-bar">
      <li class="mypage-menu">
        <%= link_to end_user_path(@end_user.id) do %>
          <i class="fas fa-journal-whills"></i> 名(迷)言</li>
        <% end %>
      <li class="mypage-menu">
        <%= link_to follow_list_path(@end_user) do %>
          <i class="fas fa-user-alt"></i><%= @end_user.followings.count %> フォロー</font>
        <% end %>
      </li>
      <li class="chosen">
        <i class="fas fa-user-friends"></i><%= @end_user.followers.count %> フォロワー</font>
      </li>
    </ul>

    <div class="d-flex flex-row flex-wrap">
     <% @end_users.each do |end_user| %>
      <div class="follow-list d-flex align-items-center">
        <div class="mr-4">
          <%= attachment_image_tag end_user, :image, fallback: "no_image.png", size: "80x80" %>
        </div>
        <div>
          <span class="h4"><%= link_to end_user.name, end_user_path(end_user.id) %></span><br>
          <%= end_user.introduction %>
        </div>
      </div>
    <% end %>
    </div>
    <div class="d-flex align-items-center justify-content-center"><%= paginate @end_users %></div>
  </div>
</div>

app/views/end_users/following.html.erb
<div class="container">
  <div class="row mx-auto">
    <div class="d-flex align-items-center justify-content-center">
      <div class="mr-4"><%= attachment_image_tag @end_user, :image, fallback: "no_image.png", size: "150x150" %></div>
      <div>
        <h3><%= @end_user.name %></h3>
        <p><%= @end_user.introduction %></p>
        <% if current_end_user == @end_user %>
          <%= link_to " プロフィールを編集", edit_end_user_path(@end_user.id), class: "fas fa-edit btn btn-success" %>
        <% end %>
        <span id="relationship"><%= render 'relationships/follow', end_user: @end_user %></span>
      </div>
    </div>
  </div>
  <div class="mypage-container mt-4">
    <ul class="mypage-bar">
      <li class="mypage-menu">
        <%= link_to end_user_path(@end_user.id) do %>
          <i class="fas fa-journal-whills"></i> 名(迷)言</li>
        <% end %>
      <li class="chosen">
        <i class="fas fa-user-alt"></i><%= @end_user.followings.count %> フォロー</font>
      </li>
      <li class="mypage-menu">
        <%= link_to follower_list_path(@end_user) do %>
          <i class="fas fa-user-friends"></i><%= @end_user.followers.count %> フォロワー</font>
        <% end %>
      </li>
    </ul>

    <div class="d-flex flex-row flex-wrap">
     <% @end_users.each do |end_user| %>
      <div class="follow-list d-flex align-items-center">
        <div class="mr-4">
          <%= attachment_image_tag end_user, :image, fallback: "no_image.png", size: "80x80" %>
        </div>
        <div>
          <span class="h4"><%= link_to end_user.name, end_user_path(end_user.id) %></span><br>
          <%= end_user.introduction %>
        </div>
      </div>
    <% end %>
    </div>
    <div class="d-flex align-items-center justify-content-center"><%= paginate @end_users %></div>
  </div>
</div>

app/views/end_users/show.html.erb
<div class="container">
  <div class="row mx-auto">
    <div class="d-flex align-items-center justify-content-center">
      <div class="mr-4"><%= attachment_image_tag @end_user, :image, fallback: "no_image.png", size: "150x150" %></div>
      <div>
        <h3><%= @end_user.name %></h3>
        <p><%= @end_user.introduction %></p>
        <% if current_end_user == @end_user %>
          <%= link_to " プロフィールを編集", edit_end_user_path(@end_user.id), class: "fas fa-edit btn btn-success" %>
        <% end %>
        <span id="relationship"><%= render 'relationships/follow', end_user: @end_user %></span>
      </div>
    </div>
  </div>
  <div class="mypage-container mt-4">
    <ul class="mypage-bar">
      <li class="chosen"><i class="fas fa-journal-whills"></i> 名(迷)言</li>
      <li class="mypage-menu">
        <%= link_to follow_list_path(@end_user) do %>
          <i class="fas fa-user-alt"></i><%= @end_user.followings.count %> フォロー</font>
        <% end %>
      </li>
      <li class="mypage-menu">
        <%= link_to follower_list_path(@end_user) do %>
          <i class="fas fa-user-friends"></i><%= @end_user.followers.count %> フォロワー</font>
        <% end %>
      </li>
    </ul>

    <div class="d-flex flex-row flex-wrap">
      <% @quotes.each do |quote|%>
      <div class="person-quote-mypage shadow mx-auto">
        <div class="mb-2 d-flex flex-row">
          <div class="mr-2">
            <%= attachment_image_tag quote, :person_image, fallback: "no_image.png", size: "50x50" %>
          </div>
          <div>
            <font color="white"><%= quote.person_name %></font><br>
            <% if quote.category.name == "ポジティブ" %>
              <span class="positive-icon"><%= quote.category.name %></span>
            <% else %>
              <span class="negative-icon"><%= quote.category.name %></span>
            <% end %>
            <font color="white"><%= l quote.created_at %></font>
          </div>
        </div>
        <%= link_to quote_path(quote.id) do %>
          <div class="person-content mt-1"><%= quote.content %></div>
        <% end %>
      </div>
      <% end %>
    </div>
    <div class="d-flex align-items-center justify-content-center"><%= paginate @quotes %></div>
  </div>
</div>

app/views/end_users/withdrawal.html.erb
<div class="container text-center">
  <h1>！退会の前に必ずご確認ください！</h1>
  <p>退会するとこのアカウントで以下の機能が利用できなくなります</p>
  <ul class="widthdrwal">
    <li>名言投稿機能</li>
    <li>コメント機能</li>
    <li>評価機能</li>
    <li>フォロー及びフォロワー機能</li>
    <li>ユーザー投稿名言</li>
  </ul>
  <p>
    ※投稿した内容は退会しても削除されません。<br>
    削除したい投稿がある場合は必ず投稿を削除した後に退会してください。
  </p>
  <%= link_to "退会する", unsubscribe_path(@end_user.id), method: :patch, class: "btn btn-danger btn-lg", data: { confirm: "本当に退会しますか？？"} %>
  <%= link_to "退会しない", end_user_path(@end_user.id), class: "btn btn-info btn-lg" %>
</div>